import { Heading, Stack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yer Da Sells Avon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack>
        <Heading>Poki Geyz</Heading>
      </Stack>
    </>
  );
};

export default Home;
